trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- script: |
    dotnet restore Api.Deployment.Sample
    dotnet publish -c Release -o bin/Release/netcoreapp3.1
    mkdir artifact
    cp -r Api.Deployment.Sample/bin/netcoreapp3.1 artifact/$(Build.SourceBranchName)
  displayName: Build Application
- task: PublishPipelineArtifact@1
  displayName: Publish Artifact
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/artifact'
    artifact: 'ApiDeploymentSample'