variables:
  project_name: 'Api.Deployment.Sample'
  netcore_version: '3.1'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'Api.Deployment.Sample/Api.Deployment.Sample.csproj'
- script: |
    pwd && ls -la
    dotnet restore Api.Deployment.Sample\
    dotnet publish Api.Deployment.Sample\ -c Release -o Api.Deployment.Sample/bin/Release/netcoreapp$(netcore_version)
    mkdir artifact
    ls artifact
    cp -r Api.Deployment.Sample/bin/Release/netcoreapp$(netcore_version) artifact/$(Build.SourceBranchName)
  displayName: Run Script
- task: PublishPipelineArtifact@1
  displayName: Publish Artifact
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/artifact'
    artifact: 'ApiDeploymentSample'    